english = [
    'You are on the menu',
    'Shop',
    'User menu',
    'Support',
    'Balance',
    'Box',
    'My purchases',
    'Refferal system',
    'To menu',
    'Box is empty. Go to the store to shop',
    'Product',
    'Price',
    'Your box',
    'Total',
    'Checkout',
    'Empty box',
    'Box was successfully cleared!',
    'Choose a delivery:',
    'Enter delivery address:',
    'Canceled. You have been returned to the menu',
    'Skip',
    'Cancel',
    'Good. Enter promo code or click "Skip"',
    'This promotional code does not exist or it does not belong to you! Enter another or click "Skip"',
    'Discount promo code',
    'activated',
    'Enter a comment to the order',
    'Cryptocurrency',
    'From balance',
    'Your order',
    'Total payable',
    'Delivery address',
    'Delivery: ',
    'Delivery method',
    'Comment',
    'Select a Payment Method:',
    'Uploading a list of cryptocurrencies',
    'Adress',
    'Choose cryptocurrency for payment',
    'Check payment',
    'Transfer',
    'To wallet',
    'After payment, do not forget to click on "Check payment". The transaction can take up to 2 hours',
    'The payment amount is below the minimum. Try adding another item to your box',
    'Payment found, manager has been notified',
    'Payment not found, please try again in 5 minutes',
    'There are not enough funds on your balance! Balance',
    'The money has been taken off the balance sheet. The order is paid, the manager received a notification.',
    'Pay',
    'The order has been created. Pay via the button below. After payment, do not forget to click on "Check payment"',
    'Payment found, I transferred your order to the manager.',
    'Payment not found. Check in 5 minutes',
    'Select a category:',
    'Select a subcategory:',
    'Unfortunately it`s empty.',
    'Product added to box',
    'Back to menu',
    'You are blocked',
    'Your',
    'Enter your question and we will answer as soon as possible:',
    'Your message has been sent! Expect a response',
    'You have been returned to the menu',
    'Reply from administrator',
    'Select a section to review:',
    'You have entered the user menu',
    'Deposit',
    'Withdraw',
    'Your balance',
    'Earned from referrals',
    'Enter the deposit amount:',
    'You didn`t enter a number! Enter an integer or number with a dot, for example:',
    'The payment amount is below the minimum. Try to make a large deposit',
    'Payment has been created. Pay using the button below. After payment, do not forget to click on "Check payment"',
    'Enter the amount to withdraw:',
    'On your balance 0 RUB',
    'Enter details, for example:',
    'You have entered more than you have! Try again',
    'Enter the amount to be withdrawn as an integer or as a decimal number, for example:',
    'Are you sure you want to apply for withdrawal',
    'For details',
    'Withdrawal request successfully submitted. You have been returned to the menu',
    'Your ref link',
    'You`ll get',
    'from referral`s purchases\n\nTotal invited',
    'No active orders found',
    'Total',
    'Active orders',
    'No completed orders found',
    'Last 2 completed orders',
    'Order pending payment:',
    'Accept',
    'Reject',
    'Add to Box',
    'To shop',
    'Product Name',
    'Description',
    'Change language',
    'You can leave a review if you wish',
    'Write a feedback',
    'Enter your review with text:',
    'Thank you. You have been returned to the menu',
    'Feedback channel',
    'Think up and enter your nickname:',
    'The minimum nickname length is 6 characters. Try again:',
    'Don`t flood',
    'The minimum deposit amount is 500 rubles. Try again',
    'Enter a rating from 1 to 5:',
    'Please enter a rating!',
    'You can add to your question. Just click the button below',
    'Enter the text and I will send it to the administrator',
    'Enter another addition to the question or click "Cancel"',
    'The maximum number of messages has been reached! Wait for a response from the administrator',
    'Thank you. We will answer you soon',
    'To reply to the administrator, click on the button below:',
    'User status',
    'New buyer',
    'pcs',
    'OK, enter the promo code or click "Skip"',
    'The minimum deposit amount is 4 usd/eur. Try again',
    'Nickname: ',
    'Login: @',
    'Balance: ',
    'Personal discount:',
    'Personal discount: ',
    'Discount coupon: ',
    'Personal stats:',
    'Purchases: ',
    'For the amount:',
    'For the amount: ',
    'Referral system stats:',
    'Ref. invited: ',
    'Ref. earned: ',
    'Absent',
    'Admin panel',
    'Products',
    'Orders',
    'Users',
    'Requests for withdrawal',
    'Bot settings',
    'Support',
    'Buyer mode',
    'Payment systems',
    'Delivery settings',
    'Change ref',
    'Setting F.A.Q',
    'Change rules',
    'Change bot token',
    'Review fee',
    'Language setting',
    'Currency settings',
    'Back to admin panel',
    'User',
    'Back',
    'Next',
    'Add delivery',
    'Question №',
    'Return to admin panel',
    'Application №',
    'Russian',
    'English',
    'You entered buyer mode',
    'You entered admin panel',
    'You have been returned to the admin panel',
    'You have entered the F.A.Q. edit panel',
    'Enter section name',
    'OK, the title will be:',
    'Enter title in English (if you already entered it in english then just duplicate it there)',
    'Enter text for section:',
    'Enter text in English (if you already entered it in english then just duplicate it there):',
    'Send a photo or press "Skip"',
    'Successfully added! You have been returned to the admin panel',
    'Text',
    'Delete',
    'Section selected:',
    'Old section name:',
    'Enter a new:',
    'Cancelled. You have been returned to the admin panel',
    'Enter the name in English (if you already entered it in english then just duplicate it there)',
    'The name has been successfully changed. You have been returned to the admin panel',
    'Old section text:',
    'Enter a new one:',
    'Enter the text in English (if you already entered it in english then just duplicate it there)',
    'The text of the section has been successfully changed. You have been returned to the admin panel',
    'Do you really want to delete the partition',
    'The section has been successfully deleted. You have been returned to the admin panel',
    'Select a category/action:',
    'Enter the category name:',
    'Enter the category name in English (if you already entered it in english then just duplicate it there):',
    'The category has been added successfully! You have been returned to the admin panel',
    'Category:',
    'Select, subcategory/action:',
    'Enter the name of the subcategory:',
    'Enter the name of the subcategory in English (if you already entered it in english then just duplicate it there):',
    'Subcategory successfully added! You have been returned to the admin panel',
    'Subcategory:',
    'Select a product/action:',
    'Return',
    'Enter a new category name:',
    'Enter a new category name in English (if you already entered it in english then just duplicate it there):',
    'The category name has been successfully changed! You have been returned to the admin panel',
    'Enter a new subcategory name:',
    'Enter a new subcategory name in English (if you already entered it in english then just duplicate it there):',
    'Enter the name of the subcategory in English (if you already entered it in english then just duplicate it there)',
    'The name of the subcategory has been successfully changed! You have been returned to the admin panel',
    'Enter the product name:',
    'Enter the name in English (if you already entered it in english then just duplicate it there):',
    'Enter the product name in English (if you already entered it in english then just duplicate it there):',
    'Enter a description for the product:',
    'Enter the description of the product in English (if you already entered it in english then just duplicate it there):',
    'Enter the price (as an integer or as a decimal number: <code>249.50</code>)',
    'Product name:',
    'Description:',
    'Price:',
    'You entered the price incorrectly! Enter the price as an integer or as a decimal number, for example: <code>249.50</code>',
    'The product has been successfully added! You have been returned to the admin panel',
    'Name',
    'Price',
    'Choose what you want to change',
    'Enter a new name for the product',
    'Enter a new name in English for the product (if you already entered it in english then just duplicate it there)',
    'Enter a new product name in English (if you already entered it in english then just duplicate it there):',
    'Enter a new description for the product',
    'Enter a new description in English for the product (if you already entered it in english then just duplicate it there)',
    'Enter a description in English (if you already entered it in english then just duplicate it there):',
    'Enter a new price for the product',
    'Enter the price as an integer or as a decimal number, for example <code>149.50</code>',
    'I received a question from a user! Look it up in the application lists',
    'Addition to the question',
    "Enter the answer to the user (the user's language is",
    'Waiting for an answer',
    'Complete',
    'The message has been sent! Send more or click "Finish" or "Wait for a response"',
    'The user has received a notification! You have been re"turned to the admin panel',
    'The matter is closed. You have been returned to the admin panel',
    'Questions from users:',
    'Support questions',
    'Manage Support agents',
    'Go back to the admin panel',
    'Add a Support agent',
    'Remove Support Agent',
    'Do you want to manage support agents or view new user questions?',
    'List of agents:',
    'Do you want to add a support agent or remove one of them?',
    'Write the id of the user you want to add to the support agents',
    'User',
    'was added to support agents',
    'was removed from support agents',
    'Error! You probably entered the id incorrectly. Try again',
    'Which support agent do you want to remove?',
    'Questions from users:',
    'Reply',
    'Return back'
    'A question from a user with an ID:',
    'Do you really want to delete the product',
    'The product has been successfully deleted! You have been returned to the admin panel',
    'Do you really want to delete a category',
    'The category has been successfully deleted! You have been returned to the admin panel',
    'Do you really want to delete a subcategory',
    'The subcategory has been successfully deleted! You have been returned to the admin panel',
    'The current percentage from the ref system:',
    'Enter a new',
    'The percentage from the ref system has been successfully changed! You have been returned to the admin panel',
    'Enter the percentage as an integer, or click "Cancel"',
    'No active orders found',
    'List of active orders:',
    'Active order №',
    'Comment:',
    'Confirm',
    'The client has received a notification and your username for communication',
    'The client blocked the bot',
    'The manager rejected the order. Contact him for details: @',
    'Send a photo of the receipt and the track code. ATTENTION, all messages that you write will be immediately received by the user',
    'The user has blocked the bot. The order has moved to completed',
    'You are in the admin panel',
    'The user has received a photo. Send another message or click "Confirm"',
    'The order has moved to completed',
    'The user has received a message. Send more or click "Confirm"',
    'Mailing to customers',
    'Mailing to everyone',
    'List of users',
    'Choose an action',
    'Enter a message for the mailing list:',
    'Send',
    'Do you want to send the message above to all users?',
    'The newsletter has started!',
    'The newsletter is completed!',
    'Page',
    'Change balance',
    'Change status',
    'Change Nickname',
    'Issue a promo code',
    'Reset ref',
    'Set a discount',
    'Send Message',
    'Ban',
    'Unban',
    'Change personal REF%',
    'User status:',
    'Nickname:',
    'Login:',
    'Balance:',
    'Personal discount',
    'Personal REF:',
    'Discount coupon:',
    'Personal statistics:\nOrders:',
    'For the amount of',
    'Ref.System statistics:\nRef. invited:',
    'Ref. earned:',
    'Enter a new buyer status:',
    'The new status has been successfully assigned!',
    'Purchases made:',
    'Referrals invited:',
    'User information:',
    'An error occurred while sending feedback to the channel',
    'You have been credited to the balance',
    'rub for a review!',
    'Order',
    'Product:\n',
    'Enter the discount percentage as an integer',
    'The discount has been successfully updated! You have been returned to the admin panel',
    'User Discount',
    'Enter a new discount:',
    'The message has been sent. Enter more or click "Cancel"',
    'Enter a message. It will be received by the user with the ID',
    'Enter a promo code:',
    'OK, enter the discount percentage (as an integer)',
    'Yes',
    'Enter the discount percentage as an integer',
    'Do you really want to issue a user with an ID',
    'Promo code:',
    'With a discount in',
    'The user has been successfully issued a promo code! You have been returned to the admin panel',
    'User balance:',
    'Enter a new balance (in rubles):',
    'Enter a new balance as an integer!',
    'The balance has been successfully changed! You have been returned to the admin panel',
    'Enter your personal ref. percentage as an integer!',
    'Personal ref. percentage changed! You have been returned to the admin panel',
    'Personal ref. user percentage:',
    'Enter a new percentage:',
    'The user is blocked. You have been returned to the admin panel',
    'You have been blocked',
    'You have been unblocked. Write /start to update',
    'The user is unblocked. You have been returned to the admin panel',
    'Delivery options',
    'Enter the delivery name:',
    'Enter the name of the delivery in English (if you already entered it in english then just duplicate it there):',
    'Enter the name in English (if you already entered it in english then just duplicate it there):',
    'Enter the delivery cost:',
    'Enter the delivery cost:',
    'Enter the delivery cost as an integer or as a decimal number. Example: <code>143.55</code>',
    'Do you really want to add a delivery option:\n<b>Name</b>:',
    'In English:',
    'Cost',
    'Delivery successfully added! You have been returned to the admin panel',
    'Enable',
    'Disable',
    'Change the name',
    'Change the cost',
    'Delete Delivery',
    'Enter the name of the delivery in English (if you already entered it in english then just duplicate it there):',
    'Delivery name:',
    'Enter a new name',
    'Currency Settings:',
    'Do you really want to reset your ref earnings?',
    'Successfully reset! You have been returned to the admin panel',
    'Prices updated',
    'Nickname successfully changed! You have been returned to the admin panel',
    'Enter a new nickname:',
    'Language Settings:',
    'Successfully changed! You have been returned to the admin panel',
    'Enter the amount that we will pay the user for the review as an integer:',
    'The token has been changed! Restart the bot to apply the changes',
    'Enter a new bot token. ATTENTION, if you enter an incorrect token, the bot will stop working',
    'Now we pays',
    'rub per review. Enter a new number or click "Cancel"',
    'Do you really want to change the bot token to',
    'The rules have been successfully updated! You have been returned to the admin panel',
    'Current rules:',
    'Enter a new rule:',
    'You have switched to the bot settings',
    'The user has received a notification! You have been returned to the admin panel',
    'Your payment request has been rejected!',
    'Your payment request has been successfully paid!',
    'Paid',
    'Refused',
    'List of withdrawal requests:',
    'The token has been successfully changed. You have been returned to the admin panel',
    'User ID:',
    'Amount:',
    'Banking details:',
    'Do you really want to change the token',
    'for',
    'Enter a new token for',
    'Select an action:',
    'Token',
    'Payment systems:',
    'Delivery successfully removed! You have been returned to the admin panel',
    'Do you really want to remove the delivery method',
    'Enter the new price as an integer or as a decimal number. Example: <code>145.31</code>',
    'The price has been successfully changed!',
    'Cost:',
    'Status:',
    'Old delivery price:',
    'Enter a new',
    'Successfully changed!',
    'Add a category',
    'New section',
    'Add a subcategory',
    'Delete Category',
    'Delete subcategory',
    'Add Product',
    'Product Description:',
    'Enabled',
    'Disabled',
    'You have been issued a promo code for',
    'discount!\nPromo code:',
    'New order. Payment from the balance. Look through the admin panel',
    'New order. Payment with QIWI. Look through the admin panel',
    'New order. Payment from ЮMoney. Look through the admin panel',
    'New order. Payment with QIWI. Look through the admin panel',
    'New order. Payment in Crypto. Look through the admin panel',
    'Add',
    'Expand Question',
    '\n(You can attach a photo of your issue. How to do it - https://clck.ru/33Lv9s)',
    '\n(You can attach a photo for user. How to do it - https://clck.ru/33Lwcp)',
    'The price has been set',
    'Physical product',
    'Create as a physical product',
    'You can create this product as a digital one. In this case, immediately after the purchase, the user will receive it along with your instructions. Click "Physical product" to skip this step or send the product and instructions to it (Write in text, you can attach <b>one</b> photo or video. If the product is a file or you need to attach more than one photo - use file sharing services and attach a link)',
    'This is digital good, it will be sent to you immediately after purchase'
]

