english = [
    'You are on the menu',
    'Shop',
    'User menu',
    'Support',
    'Balance',
    'Box',
    'My purchases',
    'Refferal system',
    'To menu',
    'Cart is empty. Go to the store to shop',
    'Product',
    'Price',
    'Your box',
    'Total',
    'Checkout',
    'Empty trash',
    'Cart was successfully cleared!',
    'Choose a shipping method:',
    'Enter shipping address:',
    'Canceled. You have been returned to the menu',
    'Skip',
    'Cancel',
    'Good. Enter promo code or click "Skip"',
    'This promotional code does not exist or it does not belong to you! Enter another or click "Skip"',
    'Discount promo code',
    'activated',
    'Enter a comment to the order',
    'Cryptocurrency',
    'From balance',
    'Your order',
    'Total payable',
    'Delivery address',
    'Delivery: ',
    'Delivery method',
    'Comment',
    'Select a Payment Method:',
    'Uploading a list of cryptocurrencies',
    'Adress',
    'Choose cryptocurrency for payment',
    'Check payment',
    'Transfer',
    'To wallet',
    'After payment, do not forget to click on "Check payment". The transaction can take up to 2 hours',
    'The payment amount is below the minimum. Try adding another item to your cart',
    'Payment found, manager has been notified',
    'Payment not found, please try again in 5 minutes',
    'There are not enough funds on your balance! Balance',
    'The money has been taken off the balance sheet. The order is paid, the manager received a notification.',
    'Pay',
    'The order has been created. Pay via the button below. After payment, do not forget to click on "Check payment"',
    'Payment found, I transferred your order to the manager.',
    'Payment not found. Check in 5 minutes',
    'Select a category:',
    'Select a subcategory:',
    'Unfortunately it`s empty.',
    'Product added to cart',
    'Back to menu',
    'You are blocked',
    'Your',
    'Enter your question and we will answer as soon as possible:',
    'Your message has been sent! Expect a response',
    'You have been returned to the menu',
    'Reply from administrator',
    'Select a section to review:',
    'You have entered the user menu',
    'Deposit',
    'Withdraw',
    'Your balance',
    'Earned from referrals',
    'Enter the deposit amount:',
    'You didn`t enter a number! Enter an integer or number with a dot, for example:',
    'The payment amount is below the minimum. Try to make a large deposit',
    'Payment has been created. Pay using the button below. After payment, do not forget to click on "Check payment"',
    'Enter the amount to withdraw:',
    'On your balance 0 RUB',
    'Enter details, for example:',
    'You have entered more than you have! Try again',
    'Enter the amount to be withdrawn as an integer or separated by a dot, for example:',
    'Are you sure you want to apply for withdrawal',
    'For details',
    'Withdrawal request successfully submitted. You have been returned to the menu',
    'Your ref link',
    'You`ll get',
    'from referral`s purchases\n\nTotal invited',
    'No active orders found',
    'Total',
    'Active orders',
    'No completed orders found',
    'Last 2 completed orders',
    'Order pending payment:',
    'Accept',
    'Reject',
    'Add to Cart',
    'To shop',
    'Product Name',
    'Description',
    'Change language',
    'You can leave a review if you wish',
    'Write a feedback',
    'Enter your review with text:',
    'Thank you. You have been returned to the menu',
    'Feedback channel',
    'Think up and enter your nickname:',
    'The minimum nickname length is 6 characters. Try again:',
    'Don`t flood',
    'The minimum deposit amount is 500 rubles. Try again',
    'Enter a rating from 1 to 5:',
    'Please enter a rating!',
    'You can add to your question. Just click the button below',
    'Enter the text and I will send it to the administrator',
    'Enter another addition to the question or click "Cancel"',
    'The maximum number of messages has been reached! Wait for a response from the administrator',
    'Thank you. We will answer you soon',
    'To reply to the administrator, click on the button below:',
    'User status',
    'New buyer',
    'pcs',
    'OK, enter the promo code or click "Skip"',
    'The minimum deposit amount is 4 usd/eur. Try again',
    'Nickname: ',
    'Login: @',
    'Balance: ',
    'Personal discount: ',
    'Discount coupon: ',
    'Personal stats:',
    'Purchases: ',
    'For the amount: ',
    'Referral system stats:',
    'Ref. invited: ',
    'Ref. earned: ',
    'Absent'
]

